trigger:
  branches:
    include:
    - master
pr:
  branches:
    include:
    - master
  drafts: false
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'

- task: Npm@1
  displayName: 'NPM: Install Extension Dependencies'
  inputs:
    workingDir: .
    verbose: false

- task: Npm@1
  displayName: 'NPM: Build Extension'
  inputs:
    command: custom
    workingDir: .
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'NPM: Install Task Dependencies'
  inputs:
    workingDir: tasks/PublishCucumberReport
    verbose: false

- task: TfxInstaller@5
  inputs:
    version: 'v0.x'

- task: PackageAzureDevOpsExtension@5
  displayName: 'TFX: Package Extension'
  inputs:
    rootFolder: .
    publisherId: MaciejMaciejewski
    extensionId: 'azure-pipelines-cucumber'
    extensionName: 'Cucumber HTML Report'
    extensionVisibility: public
    extensionPricing: free
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))

- task: PackageAzureDevOpsExtension@5
  displayName: 'TFX: Package Extension Dev'
  inputs:
    rootFolder: .
    publisherId: MaciejMaciejewski
    extensionId: 'azure-pipelines-cucumber'
    extensionTag: dev
    extensionName: 'Cucumber HTML Report Dev'
    extensionVersion: '1.0.$(Build.BuildId)'
    updateTasksVersion: true
    extensionVisibility: private
    extensionPricing: free
  condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'master'))

- task: PublishAzureDevOpsExtension@5
  displayName: 'TFX: Publish Extension Dev'
  inputs:
    connectedServiceName: Marketplace
    rootFolder: .
    publisherId: MaciejMaciejewski
    extensionId: 'azure-pipelines-cucumber'
    extensionTag: dev
    extensionName: 'Cucumber HTML Report Dev'
    extensionVersion: '1.0.$(Build.BuildId)'
    extensionVisibility: private
    extensionPricing: free
  condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'master'))

- task: ShareAzureDevOpsExtension@5
  displayName: 'TFX: Share Extension'
  inputs:
    connectedServiceName: Marketplace
    method: vsix
    vsixFile: '**.vsix'
    accounts: 'maciejmaciejewski-dev'
  condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'master'))

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/results'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/results'
  condition: succeededOrFailed()


